### PR TITLE
Make this repo an npm web module

### PR DESCRIPTION
**Pull request by gemfarmer**
I updated the package.json to allow me to deploy an npm web module. Take a look at the latest version, [1.1.10](https://www.npmjs.com/package/stickyfill-web-module)

### CODE REVIEW

**Comment by gemfarmer** [comment]
@danimalweb I received your email. Let me know if the new usage documentation is helpful. You can see examples of it in action on the useiti website. https://useiti.doi.gov. The repo is [here](https://github.com/18F/doi-extractives-data)

**Comment by danimalweb** [comment]
Thanks for the update. It works great with pure JS, but the jQuery way in the docs I couldn't get to work.
Thanks for putting this on NPM, much easier to manage.

**Comment by gemfarmer** [comment]
@danimalweb np! Glad it is working for you!

I don't know if you saw this, but we also have [some code](https://github.com/18F/doi-extractives-data/blob/dev/js/components/sticky.js) for adding a `stuck` class that was sorely needed. One day I'll add it to the polyfill itself!

**Comment by danimalweb** [comment]
Cool, looks useful. It relies on the D3 dependency right?

**Comment by gemfarmer** [comment]
@danimalweb ah! You're right! I'll be sure to get rid of the d3 dependency when I add it to this repo.

**Comment by danimalweb** [comment]
Great, if you do merge it, ping me again. Thanks!

**Pull request merged**
